version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: alwaysœ
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    expose:
      - 6379

  cve_search:
    image: cve_search
    build:
      context: .
      dockerfile: CVE-Search-Docker/docker/images/cve_search/dockerfile-cve_search
      args:
        - REPO=cve-search/cve-search
        - BRANCH=master
    hostname: cve_search
    depends_on:
      - redis
      - mongo
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=1
    ports:
      - 443:5000
    networks:
      - frontend
      - backend

  redis:
    image: cve_search-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: CVE-Search-Docker/docker/images/redis/dockerfile-redis
    volumes:
      - "./CVE-Search-Docker/.cve_search_data/cve_search_redis:/data"
    expose:
      - 6379
    networks:
      - backend

  mongo:
    image: cve_search-mongo
    hostname: mongo
    restart: always
    build:
      context: .
      dockerfile: CVE-Search-Docker/docker/images/mongodb/dockerfile-mongo
    volumes:
      - "./CVE-Search-Docker/.cve_search_data/cve_search_mongodb:/data/db"
    expose:
      - 27017
    networks:
      - backend

  exploit-db:
    build:
      context: .
      dockerfile: ./go-exploitdb/Dockerfile
    hostname: exploitDB
    command: server
    expose:
      - 1326
    networks:
      - frontend
      - backend


networks:
  frontend:
  backend: